# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwward', '0004_auto_20190318_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='content',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='design',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='usability',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='vote_submissions',
        ),
    ]
